# Generated by Django 5.0.1 on 2024-02-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='P_name',
            new_name='name',
        ),
    ]
